### PR TITLE
make the iOS version build with fake ncurses headers, but real protobuf compile artifacts

### PR DESCRIPTION
**Pull request by dariaphoebe**
iOS includes ncurses library but not headers. cheat and use the host (macos) headers. 

also, ignore any system protobuf and use the one compiled for this

### CODE REVIEW

**Comment by carloscabanero** [comment]
Daria, thanks so much to find a much better solution to fix this dependencies. I was just telling people to get it from homebrew or mac ports, but this is a better solution for the project as a whole, and compatible with the Mosh project :)

My next step in here would be to create a mosh.framework with all the .a files and the moshioscontroller header. I tried  to create a single archive library file, as it is done in other projects, but I couldn't successfully do it. So at least the mosh.framework would have the same function. 

Do you have any other suggestions for this part?

**Comment by dariaphoebe** [comment]
I can suggest additional changes to emit a single archive library, but it will probably have to wait till tomorrow. You might as well decide what to do with this, and we can use it as a base going forward

**Comment by carloscabanero** [comment]
I have pushed a new branch (cleanup) with your changes and a few tweaks from my side. I have added protobuf as a dependency here too, so everything happens in a single step. I could generate a unique library object, but unfortunately had to do it outside of LIBADD as OSX has another libtool replacing ar+ranlib, and I couldn't generate a flag or configuration that could work with LIBADD :(

But we now have a single libmoshios.framework that can be pasted straight on the project :)

**Comment by carloscabanero** [comment]
Finished with a few wrapper scripts and everything is fine now ;)

**Pull request merged**
